### PR TITLE
feat: export hf hub and vespa

### PR DESCRIPTION
**Pull request by bclavie**
Basic support for utilities to export a model from a path on disk to Huggingface Hub, as well as convert the safe tensors to VespaColBERT onnx.

### CODE REVIEW

**Comment by bclavie** [comment]
Hey @jobergum, here's a basic implementation to:

- Convert a model from disk to vespa ONNX
- Export a model to the HuggingFace hub
- Optionally, add the Vespa ONNX version of the model before exporting to the hub.

Right now it's not implemented in either of the major classes, but works as a standalone util (which I like too). It's a very rudimentary implementation, but in theory:

```python
from ragatouille.models.utils import export_to_huggingface_hub

export_to_huggingface_hub("path_to_colbert_locally", "yourusername/your_repo_name", export_vespa_onnx=True)
```

will load any Colbert model, run the conversion, then push to the hub. I've just tried it with JaColBERT and it seems to go smoothly (tmp repo for testing purposes here: https://huggingface.co/bclavie/jacolbertonnx ).

You can also just locally convert to VespaColBERT onnx:

```python
from ragatouille.models.utils import export_to_vespa_onnx
export_to_vespa_onnx("path_to_local_colbert", "out_path_for_vespa_model", out_file_name="vespa_colbert.onnx")
```
(`out_file_name` is optional, it defaults to `vespa_colbert.onnx`)


I'd be grateful if you could try it out and make sure everything with this works Vespa-side before I merge this!

**Comment by jobergum** [comment]
Wonderful! That looks great, this will work. One thing, the tokenizer should also be saved to the same directory. I do see the vocab and tokenizer_config, but not the important `tokenizer.json` file, I wonder if that is because this is a special tokenizer class?

**Comment by bclavie** [comment]
Oh that's true, I hadn't noticed! `tokenizer.json` is actually not (no longer? not sure) required when loading a tokeniser the standard HuggingFace way!

IIRC, Unless there's something specific going on, it's really just a concatenation of  `vocab.txt`, `tokenizer_config.json` and `special_tokens_map.json` so it gets automatically constructed from those.

I did expect it to be there, so you sent me on a bit of a wild hunt! It turns out that whether or not it is present by default is an artefact of the tokeniser class you're using... JaColBERT is built on [cl-tohoku/bert-base-japanese-v3](https://huggingface.co/cl-tohoku/bert-base-japanese-v3), which uses `BertJapaneseTokenizer`, which doesn't seem to export a `tokenizers.json` when using `save_pretrained`, interesting!

For Vespa purposes, would you need me to forcefully try and build a `tokenizers.json` even if the tokenizer doesn't export one by default? This shouldn't be needed if you load the tokenizer using standard HuggingFace utils like `AutoTokenizer`, but I'm not sure if you might need it for other utilities/different loading approaches.

**Comment by jobergum** [comment]
Vespa uses [dlj hf tokenizers](https://djl.ai/extensions/tokenizers/), which have standardized on using the `tokenizer.json` as the input configuration. I'll have a look at how to construct a tokenizer.json equivalent.

**Comment by bclavie** [comment]
Oh I see!

It seems like we can force exporting a `tokenizer.json` only by passing `legacy_format=False`, so I tried it out:
```python
tokenizer.save_pretrained('test', legacy_format=False)
```

And it turns out the reason BertJapaneseTokenizer doesn't export a `tokenizer.json` is because this format is technically only supported for instances of `PreTrainedTokenizerFast`, not non-fast tokenizers (JA tokenisation relies on third party libs quite a lot, so isn't implemented as a rust fast tokeniser by default):

```
ValueError: Only fast tokenizers (instances of PreTrainedTokenizerFast) can be saved in non legacy format.
```

This basically means that in the vast majority of the cases the export function would get you what you want/need, since most languages/models use a FastTokenizer implementation, so maybe it's not that big of an issue as long as it's properly documented?

----

Side note however, it looks like `dlj` relies only the Rust API?

> This is an implementation from [Huggingface tokenizers](https://github.com/huggingface/tokenizers) RUST API.

This might mean that it breaks in the cases where no rust implementation is available? In which case some models (e.g. Japanese BERT ones) would be incompatible with it? This is obviously quite niche given the overall size of the market Vespa's targeting but I'd be interested in figuring this out for sure!

**Comment by bclavie** [comment]
(in the specific case of Japanese, it looks like the fast implementation is an open issue: https://github.com/huggingface/transformers/issues/12381 )

**Comment by bclavie** [comment]
I've added a check + warning print in case a FastTokenizer cannot be found (`tokenizer.json` cannot be exported), more verbose printing when exporting to Vespa.

I think it might be worth merging as is -- it'll meet the needs of at least a large portion of users!

**Comment by jobergum** [comment]
You did a deep dive there! Deeply appreciate this work!

Adding Colbert as an embedder will now be as easy as this after one has uploaded the model to HF

```xml
<component id="colbert" type="colbert-embedder">
   <transformer-model url="https://huggingface.co/vespa-engine/col-minilm/resolve/main/model.onnx"/>
   <tokenizer-model url="https://huggingface.co/vespa-engine/col-minilm/raw/main/tokenizer.json"/>
</component>
```

**Comment by bclavie** [comment]
Great! Thanks @jobergum for the help 😄

**Pull request merged**
